# Generated by Django 2.1.7 on 2019-03-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0003_auto_20190325_2234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sentiments',
        ),
        migrations.AlterField(
            model_name='rating',
            name='rank',
            field=models.IntegerField(),
        ),
    ]
