# Generated by Django 2.1.7 on 2019-03-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0004_auto_20190325_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='rating1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rating2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='rating',
        ),
    ]
