# Generated by Django 2.1.7 on 2019-03-26 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourpackage', '0005_auto_20190325_2312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rating2',
            new_name='rating',
        ),
        migrations.DeleteModel(
            name='rating1',
        ),
    ]
